# Generated by Django 2.2 on 2019-09-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if30', models.IntegerField(default=0, verbose_name='三十附体')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('name', models.CharField(max_length=30, verbose_name='角色名')),
                ('menpai', models.CharField(max_length=20, verbose_name='门派')),
                ('cloth_grade', models.IntegerField(verbose_name='装备评分')),
                ('stone_grade', models.IntegerField(verbose_name='宝石评分')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('hp', models.IntegerField(verbose_name='血上限')),
                ('attack_heightest_name', models.CharField(max_length=30, verbose_name='最高属性攻击名称')),
                ('attack_heightest_value', models.IntegerField(verbose_name='最高属性攻击值')),
                ('others_attack', models.IntegerField(verbose_name='副属性攻击')),
                ('attack_stab', models.IntegerField(verbose_name='穿刺攻击')),
                ('huixin', models.IntegerField(verbose_name='会心')),
                ('mingzhong', models.IntegerField(verbose_name='命中')),
                ('shanbi', models.IntegerField(verbose_name='闪避')),
                ('detail_url', models.CharField(max_length=100, verbose_name='详情链接')),
                ('tili_d', models.IntegerField(default=0, verbose_name='体力鼎')),
                ('shuxing_d', models.IntegerField(default=0, verbose_name='属性鼎')),
                ('wuhun', models.IntegerField(default=0, verbose_name='武魂')),
                ('if20', models.IntegerField(default=0, verbose_name='双十珍兽')),
                ('cailiao_3', models.IntegerField(default=0, verbose_name='三级材料')),
                ('shizhuang_num', models.IntegerField(default=0, verbose_name='时装数量')),
                ('area', models.CharField(default='', max_length=200, verbose_name='区服')),
                ('shenqi_star', models.IntegerField(default=0, verbose_name='神器星级')),
                ('neiwai_max_attack', models.IntegerField(default=0, verbose_name='最高内外功')),
                ('orange_zhenyuan', models.IntegerField(default=0, verbose_name='橙色金色真元数量')),
                ('kang_heightest_name', models.CharField(default='', max_length=30, verbose_name='最高抗性名称')),
                ('kang_heightest_value', models.IntegerField(default=0, verbose_name='最高抗性值')),
                ('zuoji', models.CharField(default='', max_length=200, verbose_name='稀有坐骑')),
                ('chonglou_num', models.IntegerField(default=0, verbose_name='重楼个数')),
                ('zuoji_num', models.IntegerField(default=0, verbose_name='稀有坐骑数量')),
            ],
        ),
        migrations.CreateModel(
            name='visitNums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='名称')),
                ('visitnumsAll', models.IntegerField(default=0, verbose_name='总访问次数')),
            ],
        ),
    ]
