# Generated by Django 2.1.5 on 2019-03-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('name', models.CharField(max_length=30, verbose_name='角色名')),
                ('menpai', models.CharField(max_length=20, verbose_name='门派')),
                ('cloth_grade', models.IntegerField(verbose_name='装备评分')),
                ('stone_grade', models.IntegerField(verbose_name='宝石评分')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('hp', models.IntegerField(verbose_name='血上限')),
                ('attack_heightest_name', models.CharField(max_length=30, verbose_name='最高属性攻击名称')),
                ('attack_heightest_value', models.IntegerField(verbose_name='最高属性攻击值')),
                ('others_attack', models.IntegerField(verbose_name='副属性攻击')),
                ('attack_stab', models.IntegerField(verbose_name='穿刺攻击')),
                ('huixin', models.IntegerField(verbose_name='会心')),
                ('mingzhong', models.IntegerField(verbose_name='命中')),
                ('shanbi', models.IntegerField(verbose_name='闪避')),
                ('detail_url', models.CharField(max_length=100, verbose_name='详情链接')),
            ],
        ),
    ]
