# Generated by Django 2.2 on 2019-10-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='diaowen6',
            field=models.IntegerField(default=0, verbose_name='6级雕文数量'),
        ),
        migrations.AddField(
            model_name='role',
            name='diaowen7',
            field=models.IntegerField(default=0, verbose_name='7级雕文数量'),
        ),
    ]
