# Generated by Django 2.1.5 on 2019-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='if30',
            field=models.IntegerField(default=0, verbose_name='三十附体'),
        ),
    ]
