# Generated by Django 2.1.5 on 2019-03-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_role_if30'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='shuxing_d',
            field=models.IntegerField(default=0, verbose_name='属性鼎'),
        ),
        migrations.AddField(
            model_name='role',
            name='tili_d',
            field=models.IntegerField(default=0, verbose_name='体力鼎'),
        ),
    ]
