# Generated by Django 2.2 on 2019-10-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20191030_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='yuanbao',
            field=models.IntegerField(default=0, verbose_name='所有元宝'),
        ),
    ]
