# Generated by Django 2.1.5 on 2019-05-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20190316_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='if20',
            field=models.IntegerField(default=0, verbose_name='双十珍兽'),
        ),
        migrations.AddField(
            model_name='role',
            name='wuhun',
            field=models.IntegerField(default=0, verbose_name='武魂'),
        ),
    ]
