# Generated by Django 2.2 on 2019-10-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_role_yuanbao'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='star8',
            field=models.IntegerField(default=0, verbose_name='8，9星装备数量，最高为16'),
        ),
    ]
