# Generated by Django 2.2 on 2020-01-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_role_star8'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='shenfa',
            field=models.IntegerField(default=0, verbose_name='身法'),
        ),
        migrations.AddField(
            model_name='role',
            name='tili',
            field=models.IntegerField(default=0, verbose_name='体力'),
        ),
    ]
