# Generated by Django 2.2 on 2021-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_auto_20200117_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='xinjue',
            field=models.CharField(default='', max_length=300, verbose_name='心诀'),
        ),
    ]
