# Generated by Django 2.2 on 2021-03-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_role_xinjue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='xinjue',
            new_name='miji',
        ),
    ]
