# Generated by Django 2.2 on 2021-03-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0007_auto_20210311_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='miji',
        ),
    ]
