# Generated by Django 2.2 on 2021-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0009_role_diaowen8'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='attack_all_value',
            field=models.IntegerField(default=0, verbose_name='总属性攻击值'),
        ),
    ]
