# Generated by Django 2.2 on 2021-03-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0013_role_shizhuang_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='shizhuang_name',
        ),
    ]
