# Generated by Django 2.2 on 2021-03-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0014_remove_role_shizhuang_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='shizhuang_name',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
