# Generated by Django 2.2 on 2021-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0015_role_shizhuang_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='nb_xinjue_name',
            field=models.CharField(default='', max_length=10000, verbose_name='稀有心决名称'),
        ),
        migrations.AddField(
            model_name='role',
            name='nb_xinjue_num',
            field=models.IntegerField(default=0, verbose_name='稀有心决数量'),
        ),
        migrations.AlterField(
            model_name='role',
            name='shizhuang_name',
            field=models.CharField(default='', max_length=10000, verbose_name='时装颜色'),
        ),
    ]
