# Generated by Django 2.2 on 2021-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0017_auto_20210614_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='attack_all_value',
            field=models.IntegerField(default=0, verbose_name='总属性攻击值'),
        ),
        migrations.AddField(
            model_name='role',
            name='nb_xinjue_name',
            field=models.CharField(default='', max_length=10000, verbose_name='稀有心决名称'),
        ),
        migrations.AddField(
            model_name='role',
            name='nb_xinjue_num',
            field=models.IntegerField(default=0, verbose_name='稀有心决数量'),
        ),
        migrations.AddField(
            model_name='role',
            name='shizhuang_name',
            field=models.CharField(default='', max_length=10000, verbose_name='时装颜色'),
        ),
    ]
