# Generated by Django 2.2 on 2021-07-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0019_role_nb_animal_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='nb_animal_num',
        ),
        migrations.RemoveField(
            model_name='role',
            name='zuoji_num',
        ),
    ]
