# Generated by Django 2.2 on 2021-07-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0020_auto_20210718_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='nb_animal_num',
            field=models.IntegerField(default=0, verbose_name='强力珍兽数量'),
        ),
        migrations.AddField(
            model_name='role',
            name='zuoji_num',
            field=models.IntegerField(default=0, verbose_name='稀有坐骑数量'),
        ),
    ]
