# Generated by Django 2.2 on 2021-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0021_auto_20210718_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='yigudan',
            field=models.IntegerField(default=0, verbose_name='移骨丹'),
        ),
    ]
