# Generated by Django 2.2 on 2019-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190524_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='statement',
            field=models.CharField(default='', max_length=100),
        ),
    ]
